version: '3'

services:
  redis:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    container_name: mymongo
    ports:
      - "27017:27017"
      - "27018:27018"
  cassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7687:7687"
      - "7473:7473"
      - "7474:7474"
    container_name: myneo4j