version: '3'

services:
  python:
    image: quay.io/jupyter/datascience-notebook
    container_name: mypython
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8888:8888"
  redis:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"
  mongo:
    image: mongo:4
    container_name: mymongo
    ports:
      - "27017:27017"
      - "27018:27018"
  cassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
  orientdb:
    image: orientdb:2.2
    container_name: myorientdb
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
    ports:
      - "2424:2424"
      - "2480:2480"
