version: '3'

services:
  redis:
    image: redis
    container_name: myredis
  mongo:
    image: mongo
    container_name: mymongo
  cassandra:
    image: cassandra
    container_name: mycassandra
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7687:7687"
      - "7473:7473"
      - "7474:7474"
    container_name: myneo4j